"""Run reproducible vehicle-count experiments and optionally export JSON/Markdown."""

import argparse
import json
from dataclasses import asdict
from pathlib import Path

from simulator.engine import SimulationEngine
from simulator.scenarios.amhs import create_amhs_scenario


def compare_vehicles(seed: int = 42) -> list[dict]:
    rows = []
    for count in (1, 3, 6):
        scenario = create_amhs_scenario(count, seed=seed)
        result = SimulationEngine(seed).run_scenario(scenario)
        rows.append(
            {
                "vehicle_count": count,
                "scenario": asdict(scenario),
                "finished_at": result.finished_at,
                "kpis": asdict(result.kpis),
                "transport_jobs": [asdict(job) for job in result.transport_jobs],
                "events": [asdict(event) for event in result.events],
            }
        )
    return rows


def render_report(rows: list[dict]) -> str:
    lines = [
        "# Day 4 AMHS comparison",
        "",
        "Generated by `python -m app.simulation.amhs`. All durations are minutes.",
        "20 lots arrive at time zero; processing takes 2 / 4 / 1 minutes across",
        "Lithography / Etching / Inspection. Each transfer takes 5 minutes.",
        "FIFO dispatch with default Hot/aging rules; all lots Normal, no failures.",
        "",
        "| Vehicles | Jobs | Travel | Transport wait | Vehicle utilization | "
        "Avg cycle | Lots/hour |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        k = row["kpis"]
        lines.append(
            f"| {row['vehicle_count']} | {k['transport_job_count']} | "
            f"{k['average_transport_time']:.2f} | {k['average_transport_waiting_time']:.2f} | "
            f"{k['vehicle_utilization']:.1%} | {k['average_cycle_time']:.2f} | "
            f"{k['throughput_per_hour']:.2f} |"
        )
    lines += [
        "",
        "| Vehicles | Lithography utilization | Etching utilization | Inspection utilization |",
        "| ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        values = " | ".join(f"{m['utilization']:.1%}" for m in row["kpis"]["machines"])
        lines.append(f"| {row['vehicle_count']} | {values} |")
    lines += [
        "",
        "One vehicle creates transport congestion and leaves downstream machines waiting for lots.",
        "Three vehicles reduce transport waiting; Etching becomes the processing bottleneck",
        "(4 minutes per lot versus 2 and 1). Six vehicles do not further improve throughput",
        "for this workload. More vehicles therefore do not always increase throughput.",
        "Utilization includes startup and drain time; machine idle time alone is not a",
        "dedicated starvation metric. These are finite-workload results, not steady-state rates.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--json", type=Path)
    args = parser.parse_args()
    rows = compare_vehicles(args.seed)
    report = render_report(rows)
    print(report, end="")
    if args.output:
        args.output.write_text(report, encoding="utf-8")
    if args.json:
        args.json.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
